name: urbix_final_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_blue: ^0.8.0
  flutter_launcher_icons: ^0.13.1


  latlng: ^1.0.0
  flutter_map: any
  flutter_map_marker_cluster: any
  flutter_map_tile_caching: ^8.0.1

  flutter_svg: ^2.0.7
  pull_to_refresh: ^2.0.0
  url_launcher: ^6.1.14

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/UrbixLogo.png"
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
